export const events = {
  nodeDragStart: 'nodeDragStart',
  nodeDragEnd: 'nodeDragEnd',
  nodeHover: 'nodeHover',
  nodeUnHover: 'nodeUnHover',
  nodeRightClick: 'nodeRightClick',
  nodeSelect: 'nodeSelect',
  nodeUnselect: 'nodeUnselect',
  portHover: 'portHover',
  edgeCreate: 'edgeCreate',
  edgeRightClick: 'edgeRightClick',
  canvasClick: 'canvasClick',
  edgeUnHover: 'edgeUnHover',
  edgeHover: 'edgeHover',
  edgeClick: 'edgeClick',
};
